// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DefaultConnection`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Server=tcp:lemasterworks.database.windows.net,1433;Initial Catalog=MTG;Persist Security Info=False;User ID=tlemaster;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace MTG.Entities.Models
{


    /// <summary>
    /// A class which represents the testCard table.
    /// </summary>
	[Table("testCard")]
    public partial class testCard
    {
        public virtual string name { get; set; }
        public virtual string manaCost { get; set; }
        public virtual int? cmc { get; set; }
        public virtual string colors { get; set; }
        public virtual string type { get; set; }
        public virtual string supertypes { get; set; }
        public virtual string subtypes { get; set; }
        public virtual string rarity { get; set; }
        public virtual string text { get; set; }
        public virtual string flavor { get; set; }
        public virtual string artist { get; set; }
        public virtual int? number { get; set; }
        public virtual int? power { get; set; }
        public virtual int? toughness { get; set; }
        public virtual string layout { get; set; }
        public virtual int? multiverseid { get; set; }
        public virtual string imageName { get; set; }
        public virtual string id { get; set; }
    }

    /// <summary>
    /// A class which represents the startTest table.
    /// </summary>
	[Table("startTest")]
    public partial class startTest
    {
        public virtual string cardName { get; set; }
        public virtual string manaCost { get; set; }
        public virtual string cmc { get; set; }
    }

    /// <summary>
    /// A class which represents the employees table.
    /// </summary>
	[Table("employees")]
    public partial class employee
    {
        public virtual string Name { get; set; }
        public virtual string Gender { get; set; }
        public virtual string Company { get; set; }
        public virtual string Email { get; set; }
    }

    /// <summary>
    /// A class which represents the Sets table.
    /// </summary>
	[Table("Sets")]
    public partial class Set
    {
        public virtual string Code { get; set; }
        public virtual string Name { get; set; }
        public virtual DateTime? ReleaseDate { get; set; }
        public virtual string Border { get; set; }
        public virtual string Type { get; set; }
        public virtual string Block { get; set; }
        public virtual string OldCode { get; set; }
    }

    /// <summary>
    /// A class which represents the Cards table.
    /// </summary>
	[Table("Cards")]
    public partial class Card
    {
        public virtual string Set { get; set; }
        public virtual int? ID { get; set; }
        public virtual string Name { get; set; }
        public virtual string ManaCost { get; set; }
        public virtual string ConvertedManaCost { get; set; }
        public virtual string ColorIdentity { get; set; }
        public virtual string Colors { get; set; }
        public virtual string Type { get; set; }
        public virtual string Types { get; set; }
        public virtual string SubTypes { get; set; }
        public virtual string Rarity { get; set; }
        public virtual string Text { get; set; }
        public virtual string Flavor { get; set; }
        public virtual string Artist { get; set; }
        public virtual string Number { get; set; }
        public virtual string Power { get; set; }
        public virtual string Toughness { get; set; }
        [NotMapped]
        public virtual string SetName { get; set; }
        [NotMapped]
        public virtual bool Hovering { get; set; }
        [NotMapped]
        public virtual string src { get; set; }
        [NotMapped]
        public virtual string url { get; set; }
        [NotMapped]
        public virtual int Amount { get; set; }
    }

    /// <summary>
    /// A class which represents the Users table.
    /// </summary>
	[Table("Users")]
    public partial class User
    {
        public virtual int UserId { get; set; }
        public virtual string Email { get; set; }

    }
}
